// Generated by Xata Codegen 0.23.5. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "judgments",
    columns: [
      { name: "JudgementNo", type: "string" },
      { name: "Url", type: "string" },
      { name: "CaseNumber", type: "string" },
      { name: "Summary", type: "text" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Judgments = InferredTypes["judgments"];
export type JudgmentsRecord = Judgments & XataRecord;

export type DatabaseSchema = {
  judgments: JudgmentsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://satish-s-workspace-6midd6.us-east-1.xata.sh/db/judgment",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
